name: design_system
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard_black.otf
          weight: 900
        - asset: assets/fonts/pretendard_bold.otf
          weight: 700
        - asset: assets/fonts/pretendard_extrabold.otf
          weight: 800
        - asset: assets/fonts/pretendard_extralight.otf
          weight: 200
        - asset: assets/fonts/pretendard_light.otf
          weight: 300
        - asset: assets/fonts/pretendard_medium.otf
          weight: 500
        - asset: assets/fonts/pretendard_regular.otf
          weight: 400
        - asset: assets/fonts/pretendard_semibold.otf
          weight: 600
        - asset: assets/fonts/pretendard_thin.otf
          weight: 100

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
