name: flooding_app_design_system
description: "flooding_app에서 사용할 design_system."
version: 1.0.1
repository: https://github.com/flooding-kr/flooding-app-designSystemLibrary

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/image/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard_black.otf
          weight: 900
        - asset: assets/fonts/pretendard_bold.otf
          weight: 700
        - asset: assets/fonts/pretendard_extrabold.otf
          weight: 800
        - asset: assets/fonts/pretendard_extralight.otf
          weight: 200
        - asset: assets/fonts/pretendard_light.otf
          weight: 300
        - asset: assets/fonts/pretendard_medium.otf
          weight: 500
        - asset: assets/fonts/pretendard_regular.otf
          weight: 400
        - asset: assets/fonts/pretendard_semibold.otf
          weight: 600
        - asset: assets/fonts/pretendard_thin.otf
          weight: 100
