name: Flutter Develop CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Flutter repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.2

      - name: Checking Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Test Package
        run: flutter packages pub publish --dry-run

      - name: Set timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      ## ✅ 성공 알림 (Push)
      - name: Notify Success for Push
        if: github.event_name == 'push' && success()
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          SUCCESS_FLUTTER_IMAGE: ${{ secrets.SUCCESS_FLUTTER_IMAGE }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          DATA=$(jq -n --arg content "<@749992025985777755>, <@1042669793481871361>, <@930099449307467786>" \
            --arg title "CI 성공 :)" \
            --arg desc "** COMMIT MESSAGE **\n> [${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})\n" \
            --arg timestamp "${{ env.TIMESTAMP }}" \
            --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --arg author_name "${{ github.event.sender.login }}" \
            --arg author_url "${{ github.event.sender.html_url }}" \
            --arg image_url "${{ secrets.SUCCESS_FLUTTER_IMAGE }}" \
            --arg repo "> [${{ github.repository }}](https://github.com/${{ github.repository }})\n" \
            --arg branch "> [${{ github.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.ref_name }})" \
            --arg workflow "> [CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
            '{
              "content": $content,
              "embeds": [
                {
                  "title": $title,
                  "description": $desc,
                  "color": 46335,
                  "timestamp": $timestamp,
                  "url": $url,
                  "author": { "name": $author_name, "url": $author_url },
                  "image": { "url": $image_url },
                  "fields": [
                    { "name": "Repository", "value": $repo },
                    { "name": "Branch", "value": $branch, "inline": false },
                    { "name": "Workflow", "value": $workflow, "inline": false }
                  ]
                }
              ]
            }')

          echo "Generated JSON: $DATA"  # Debugging
          curl -X POST -H 'Content-type:application/json' -d "$DATA" "${{ secrets.DISCORD_WEBHOOK_URL }}"

      ## ✅ 성공 알림 (Pull Request)
      - name: Notify Success for PR
        if: github.event_name == 'pull_request' && success()
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          SUCCESS_FLUTTER_IMAGE: ${{ secrets.SUCCESS_FLUTTER_IMAGE }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          DATA=$(jq -n --arg content "<@749992025985777755>, <@1042669793481871361>, <@930099449307467786>" \
            --arg title "CI 성공 :)" \
            --arg desc "** Pull Request **\n> [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\n" \
            --arg timestamp "${{ env.TIMESTAMP }}" \
            --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --arg author_name "${{ github.event.sender.login }}" \
            --arg author_url "${{ github.event.sender.html_url }}" \
            --arg image_url "${{ secrets.SUCCESS_FLUTTER_IMAGE }}" \
            --arg repo "> [${{ github.repository }}](https://github.com/${{ github.repository }})\n" \
            --arg branch "> [${{ github.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.ref_name }})" \
            --arg workflow "> [CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
            '{
              "content": $content,
              "embeds": [
                {
                  "title": $title,
                  "description": $desc,
                  "color": 46335,
                  "timestamp": $timestamp,
                  "url": $url,
                  "author": { "name": $author_name, "url": $author_url },
                  "image": { "url": $image_url },
                  "fields": [
                    { "name": "Repository", "value": $repo },
                    { "name": "Branch", "value": $branch, "inline": false },
                    { "name": "Workflow", "value": $workflow, "inline": false }
                  ]
                }
              ]
            }')

          echo "Generated JSON: $DATA"  # Debugging
          curl -X POST -H 'Content-type:application/json' -d "$DATA" "${{ secrets.DISCORD_WEBHOOK_URL }}"

      ## ❌ 실패 알림
      - name: Notify Failure
        if: failure()
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          FAIL_FLUTTER_IMAGE: ${{ secrets.FAIL_FLUTTER_IMAGE }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          DATA=$(jq -n --arg content "<@749992025985777755>, <@1042669793481871361>, <@930099449307467786>" \
            --arg title "CI 실패 :(" \
            --arg desc "** ${{
              github.event_name == 'push' && 'COMMIT MESSAGE' || 'Pull Request' 
            }} **\n> [${{ 
              github.event_name == 'push' && github.event.head_commit.message || github.event.pull_request.title 
            }}](${{ 
              github.event_name == 'push' && github.event.head_commit.url || github.event.pull_request.html_url 
            }})\n" \
            --arg timestamp "${{ env.TIMESTAMP }}" \
            --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --arg author_name "${{ github.event.sender.login }}" \
            --arg author_url "${{ github.event.sender.html_url }}" \
            --arg image_url "${{ secrets.FAIL_FLUTTER_IMAGE }}" \
            '{
              "content": $content,
              "embeds": [
                {
                  "title": $title,
                  "description": $desc,
                  "color": 16711680,
                  "timestamp": $timestamp,
                  "url": $url,
                  "author": { "name": $author_name, "url": $author_url },
                  "image": { "url": $image_url }
                }
              ]
            }')

          echo "Generated JSON: $DATA"  # Debugging
          curl -X POST -H 'Content-type:application/json' -d "$DATA" "${{ secrets.DISCORD_WEBHOOK_URL }}"
